### ISSUE TITLE
АПИ для авторизации

### ISSUE THREAD

**Issue by ya7on** [donkey-engine/donkey-engine#3]
Сделать простую авторизацию и регистрацию пользователей
**Стоит еще обсудить какую аутентификацию использовать: по токену или сессии**

**Comment by ya7on** [comment]
Решили делать аутентификацию по токену

**Comment by tmcgroul** [comment]
тема решения аутентификации по токену не раскрыта

**Comment by ya7on** [comment]
Согласен. Нужно еще подумать
