### ISSUE TITLE
Хранить пароли в зашифрованном виде

### ISSUE THREAD

**Issue by tmcgroul** [donkey-engine/donkey-engine#48]
Механизм проверки пароля, который используется при аутентификации ожидает чистый пароль, чтобы потом его зашифровать и сравнить с тем, который хранится в базе.

**Comment by tmcgroul** [comment]
@pyKorgot @BehindLoader парни ну надо разобраться как так

**Comment by ya7on** [comment]
@tmcgroul предлагаешь передавать пароль на бекенд сразу в зашифрованном виде? 🤔

**Comment by tmcgroul** [comment]
@BehindLoader нет, шифровать где-то в этом [месте](https://github.com/donkey-engine/donkey-engine/blob/master/accounts/views.py#L56)

**Comment by ya7on** [comment]
А. То есть там пароль не шифруется при создании пользователя? Надо поправить

**Comment by tmcgroul** [comment]
всё так

**Comment by ya7on** [comment]
Сделаешь?

**Comment by tmcgroul** [comment]
могу
вечерком запилю тогда
