### ISSUE TITLE
При запуске сервера останавливать другие серверы пользователя

### ISSUE THREAD

**Issue by ya7on** [donkey-engine/donkey-engine#76]
Сейчас пользователи могут запускать сотни тысяч серверов

**Comment by tmcgroul** [comment]
> Сейчас пользователи могут запускать сотни тысяч серверов

как что-то плохое...
а как на фронте статусы серверов обновлять? сейчас там костыль с while и setTimeout

**Comment by ya7on** [comment]
Нужно как-то эту штуку продумать. Мб какие-то уведомления сделать
