### ISSUE TITLE
Авторизация через другие сервисы

### ISSUE THREAD

**Issue by ya7on** [donkey-engine/donkey-engine#91]
Для начала только через Discord, но в планах добавить другие сервисы

**Comment by tmcgroul** [comment]
@BehindLoader a chto luchwe:
api/auth/discord-redirect/
ili
api/auth/discord/redirect/
mm?

**Comment by ya7on** [comment]
Мне оба варианта не кажутся плохими. Но второй больше нравится

**Comment by tmcgroul** [comment]
a kak bit' kogda username pol'zovatelya s discorda sovpadaet s uje zaregistrirovannim pol'zovatelem?
mojno predlagat' pol'zovatelyu vibirat' drugoy username
a vawe ya bi poka eto ne stal delat'....

**Comment by ya7on** [comment]
Что именно не стал бы?

**Comment by tmcgroul** [comment]
> Что именно не стал бы?

predlagat' pol'zovatelyu chto-libo
prosto govorit' chto username zanyat

**Comment by ya7on** [comment]
Ну можно пока что, но мне кажется, что это станет проблемой потом как-нибудь
